[package]
name = "mcp_server_slack"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/slack_model_context.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
serde = "1.0"
schemars = "0.8"
